#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (C) 2012 Hydriz
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import re
import urllib

# Global configuration
# S3-like API keys (Get one at http://archive.org/account/s3.php)
accesskey = ""
secretkey = ""
# Dump files
url = "http://ftpmirror.your.org/pub/wikimedia/imagedumps/tarballs/incrs/tarballs/"
listurl = "http://ftpmirror.your.org/pub/wikimedia/imagedumps/tarballs/incrs/lists/"
incrdate = ""
# Archive.org matters
collection = ""
mediatype = ""
# Other stuff
wikifilelist = "result.txt" # /path/to/result.txt
sizehint = "107374182400" # 100GB
tempdir = ""

# Nothing to change below...
host = url + incrdate + "/"
listhost = listurl + incrdate + "/"
filelist = {
	'local-media-incr-1.tar',
	'remote-media-incr-1.tar',
}
gzfilelist = {
	'local-media-incr.gz',
	'remote-media-incr.gz',
}
wikirightnow = ""
count = 0
def welcome():
	print "Archiving the incremental dumps tarballs together with the lists."

def bye():
	print "Done uploading. Bye!"

def listofwikis():
	global count, wikirightnow
	wikilist = open(wikifilelist).read().splitlines()
	for wiki in wikilist:
		count = 0
		for tarfile in filelist:
			listfile = ''.join(tarfile)
			nicename = wiki + "-" + incrdate + "-" + listfile
			wikirightnow = wiki
			wgetthefile(nicename)
			upload(nicename)
		for gzfile in gzfilelist:
			listgzfile = ''.join(gzfile)
			nicegzname = wiki + "-" + incrdate + "-" + listgzfile
			wikirightnow = wiki
			wgetthelist(nicegzname)
			upload(nicegzname)

def upload(thedumpfile):
	global count
	if (count == 0):
		curl = ['curl', '--retry 20', '--location',
				'--header', "'x-amz-auto-make-bucket:1'",
				'--header', "'x-archive-meta01-collection:%s'" % (collection),
				'--header', "'x-archive-meta-mediatype:%s'" % (mediatype),
				'--header', "'x-archive-queue-derive:0'",
				'--header', "'x-archive-size-hint:%s'" % (sizehint),
				'--header', "'x-archive-meta-title:Wikimedia media incremental dump files for %s on %s'" % (wikirightnow, incrdate),
				'--header', "'x-archive-meta-description:This is the incremental media dump files for %s that is generated by Wikimedia on %s.'" % (wikirightnow, incrdate),
				'--header', '"authorization: LOW %s:%s"' % (accesskey,secretkey),
				'--upload-file', "%s http://s3.us.archive.org/mediatar-%s-%s/%s" % (thedumpfile,wikirightnow, incrdate,thedumpfile),
				]
		os.chdir(tempdir)
		os.system(' '.join(curl))
		rmcmd = "rm " + thedumpfile
		os.system(rmcmd)
		os.system("sleep 60")
		count += 1
	else:
		curl = ['curl', '--retry 20', '--location',
				'--header', "'x-archive-queue-derive:0'",
				'--header', '"authorization: LOW %s:%s"' % (accesskey,secretkey),
				'--upload-file', "%s http://s3.us.archive.org/mediatar-%s-%s/%s" % (thedumpfile,wikirightnow, incrdate,thedumpfile),
				]
		os.chdir(tempdir)
		os.system(' '.join(curl))
		rmcmd = "rm " + thedumpfile
		os.system(rmcmd)

def wgetthefile(thedumpfile):
	os.chdir(tempdir)
	os.system("wget -c " + host + thedumpfile)

def wgetthelist(thelistfile):
	os.chdir(tempdir)
	os.system("wget -c " + listhost + thelistfile)

def process():
	welcome()
	listofwikis()
	bye()

process()
